proxmox_guest_nodes:
  hosts:
    pve01:
      ansible_host: 192.168.10.11
    pve02:
      ansible_host: 192.168.10.12
    pve03:
      ansible_host: 192.168.10.13

  vars:
    ansible_user: root

proxmox_personal_nodes:
  hosts:
    pve01:
      ansible_host: 192.168.68.11
    pve02:
      ansible_host: 192.168.68.12
    pve03:
      ansible_host: 192.168.68.13

  vars:
    ansible_user: root
