---
- name: "ロケールを生成する({{ development_locale }})"
  community.general.locale_gen:
    name: "{{ development_locale }}"
    state: present
  become: true

- name: デフォルトロケールを設定する
  ansible.builtin.lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: "LANG={{ development_locale }}"
    create: true
    mode: "0644"
  become: true
