---
- name: パッケージを更新する
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: 必要なパッケージ類をインストールする
  ansible.builtin.apt:
    name:
      - git
      - curl
      - cockpit
    state: present
  become: true
